### ISSUE TITLE
Condition for X-Snooze doesn't show date options

### ISSUE THREAD

**Issue by malob** [prenagha/snooze.mmbundle#1] opened 2018-06-19 22:32 UTC
I'm trying to setup this bundle. I've got the “Later” folder setup, and messages are successfully being added to the folder and the `X-Snooze` attribute is applied with the right datetime.

However, I can't get the Smart Mailbox to work. When I go to set the condition, the options that appear are the ones for strings:
<img width="937" alt="screen shot 2018-06-19 at 15 23 21" src="https://user-images.githubusercontent.com/2914269/41627369-ebc76820-73d4-11e8-816d-83690b765091.png">

I tried using “within last 0 days” in the text filed, but it didn't work.

I assume it's supposed to show the same options as when filtering on Date. Like this:
<img width="937" alt="screen shot 2018-06-19 at 15 28 45" src="https://user-images.githubusercontent.com/2914269/41627542-87343270-73d5-11e8-98e4-2a81174606f5.png">

Any help you could provide would be greatly appreciated. This is such an awesome bundle 😄.

**Comment by prenagha** [comment] 2018-06-19 23:24
I have an open bug report with MailMate @freron on this. Haven't heard back. Feel free to ping MailMate support and ask as well.

**Comment by freron** [comment] 2018-06-20 09:55
Yeah, sorry about not getting back on that. In case it's useful, you might actually be able to hack it by editing the Mailboxes.plist file directly. Use the Date header in the GUI, quit MailMate, and then edit the Mailboxes.plist file to replace `#date` with `x-snooze`. But you probably won't be able to edit it with the GUI without destroying the condition (I think).

**Comment by malob** [comment] 2018-06-26 20:23
I've just tried this and still can't get it to work.

To try and diagnose the problem I tried to make it simpler and just filter on `x-snooze`'s existence for all messages. Interestingly I can't even get messages to appear at all in my smart mailbox when doing this.

Here's the relevant smart mailbox definition from Mailboxes.plist:
```plist
{ countKey = "all";
  filter = "x-snooze exists";
  name = "Snooze";
  parentUUID = "MAILBOXES";
  set = "ALL_MESSAGES";
  uuid = "40786E56-BEC3-4B26-829D-AF6DDBCFCC04";
},
```

I tried:
  * `filter = "x-snooze exists";`
  * `filter = "X-Snooze exists";`
  * `filter = "#x-snooze exists";`
  * `filter = "#X-Snooze exists";`

The smart mailbox contains no messages for all of these. Each time I closed MailMate, made the change the Mailboxes.plist, then opened it again.

I also made sure that I did have messages with `X-Snooze` defined in the header. For example I have one message with the following in the header (found by viewing the messages raw source): `X-Snooze: Fri, 01 Jun 2018 09:00:00 -0700`.

As a sanity check I closed MailMate and changed the filter line to `filter = "#date exists";` and it worked as expected, i.e., all my messages showed up. And `!exists` causes no messages to show up.

Any idea what's going on?

---

> But you probably won't be able to edit it with the GUI without destroying the condition (I think).

This is correct.

**Comment by freron** [comment] 2018-06-28 09:05
@malob Sounds like the new header is not (correctly) indexed by MailMate. I'll see if I can reproduce it.

**Comment by freron** [comment] 2018-06-28 09:47
@malob Ok, the issue is triggered by the header names not being lower-cased (which MailMate internally expects them to be). I've improved the code to automatically handle this in the next update (r5503+). In my quick test, I could now search for the x-snooze header.

**Comment by malob** [comment] 2018-06-28 16:07
@freron, amazing! I'll test it when my MailMate updates (I get beta updates), and report back here.

**Comment by prenagha** [comment] 2018-07-02 22:12
Ok, I changed the header name to lower case (see b3aa04cb3fad3868a6828dafd294cbdb03c339a3)
So now the indexing seems to work, I can have a Smart Mailbox with criteria of `x-snooze exists` and it finds the message
Remaining piece that doesn't work is MailMate is treating `x-snooze` as a string, so I can't do the criteria I really need which is `x-snooze is not within last 0 days`
@freron any way for me to get MailMate to treat `x-snooze` as a date header?

**Comment by jmazzi** [comment] 2018-07-02 22:28
@prenagha @freron this worked for me. Create a `/Users/justin/Library/Application Support/MailMate/Resources/headersPopUp.plist` file with this content:

```
{
        popUpHeaders = (
                { title = "From"; },
                { title = "Recipient (To, Cc, Bcc)"; specifier = "#recipient"; },
                { title = "To"; },
                { title = "Any Address"; specifier = "#any-address"; },
                // { title = "Cc"; },
                // { title = "In-Reply-To"; },
                { title = "X-Snooze"; specifier = "#date"; },
                { title = "Subject"; },
                { title = "Date"; specifier = "#date"; },
                { title = "Filename"; specifier = "#filename"; allBodyParts = 1; },
                { title = "Mailer"; specifier = "#mailer"; },
                { /************************/ },
                { title = "Tags/Keywords"; specifier = "#flags.flag"; },
                { title = "Tags"; specifier = "##tags.tag"; },
                { /************************/ },
                // Note: allBodyParts is currently not used (but hardcoded for the following 3 in code -- and Filename above)
                { title = "Unquoted Body Text"; specifier = "#unquoted"; allBodyParts = 1; },
                { title = "Quoted Body Text"; specifier = "#quoted"; allBodyParts = 1; },
                { title = "Common Headers or Body"; specifier = "#common"; allBodyParts = 1; },
        );
}
```

I copied the file from `/Applications/MailMate.app/Contents/Resources/headersPopUp.plist` into `/Users/justin/Library/Application Support/MailMate/Resources` and added this line: 

```
{ title = "X-Snooze"; specifier = "#date"; },
```

**Comment by prenagha** [comment] 2018-07-03 00:52
@jmazzi tried what you posted above, that makes it show up in the Mailbox condition editor with date like parts (day, formatted...) but when I choose X-Snooze and it goes back to the main UI it says `Date` and it records as `#date` in `Mailboxes.plist`. @freron let us know if there is some way to get `x-snooze` properly recognized as a date header so can write a mailbox condition `x-snooze is not within last 0 days`

**Comment by freron** [comment] 2018-07-03 09:49
@prenagha: This requires a feature I haven't implemented yet. Preferences provided by bundles which could, e.g., be the types of custom headers or custom message list columns (and many other things). It's an important feature, but it's *not* going to be implemented soon. In order for you to continue experimenting with the snoozing bundle I've hardcoded that x-snooze is treated as a date header (next update). Note that this won't continue to work, but when it no longer works it'll be because preferences are supported :)

Note that it'll probably only work well if the x-snooze header uses dates without zones, that is, the date can be assumed to be GMT/+0000.

**Comment by prenagha** [comment] 2018-07-03 14:08
I am using `date` to output RFC 2822 date and time output format in my local timezone, like 
`> date -R -v0M -v0S -v+1d -v9H`
`Wed, 04 Jul 2018 09:00:00 -0400`
And am looking for the mailbox condition to recognize when that date is in the past, relative to my local timezone.
@freron Will the date like above be ok or are you saying I need to convert that date to GMT and output  `Wed, 04 Jul 2018 13:00:00 +0000` to get it to work?

Also, I am on 2.0BETA (build 6113).
Do I just wait for a normal beta release or do I get these changes sooner somehow?

**Comment by freron** [comment] 2018-07-04 08:59
You need to use `-u` to get +0000, but this clashes with hardcoding the hours. Hmm, I think you might have to call date twice. Or google a solution :)

Release: The fastest is to switch to the 1.x releases: https://updates.mailmate-app.com/archives/MailMate_r5504.tbz

(I haven't released the snooze-hardcoded version yet.)

**Comment by prenagha** [comment] 2018-07-05 14:52
Thanks @freron , making some progress but having trouble with the mailbox criteria now...
Updated MailMate to _Version 2.0BETA (6114)_
Created [test command](https://github.com/prenagha/snooze.mmbundle/blob/e8471539afa67fbecfd10e71f6c3fdcf41082e30/Support/bin/test.sh#L12) that sets the `x-snooze` header to `Sun, 01 Jul 2018 09:00:00 +0000`
Ran the command on a message, verified in _Raw Message_ view the header is set to `X-Snooze: Sun, 01 Jul 2018 09:00:00 +0000`
Open Mailbox with source of `/Later` folder, the test message appears
However when I try to use mailbox criteria I do not get what I expect:
* `X-Snooze is not within last z days` returns nothing regardless of z
* `X-Snooze is within last z days` returns nothing regardless of z
* `X-Snooze is exactly z` returns nothing regardless of z
* `X-Snooze is after 7/5/18` returns the message
* `X-Snooze is before 7/5/18` returns nothing

Ideas on what to do to get the date criteria working properly?

**Comment by freron** [comment] 2018-07-05 18:25
Oh, I should have warned about that. MailMate expects date headers to be in this format: `2017-12-24 12:45:38`. Although `Date` is not in that format, MailMate actually uses a virtual header named `#date` which is. This is because it requires quite an elaborate heuristic to parse real (often invalid) date headers as gracefully as possible.

**Comment by prenagha** [comment] 2018-07-05 19:29
Ok so format the header as `yyyy-MM-dd HH:mm:SS`, I can do that I am sure.
I know not to specify the timezone in the string itself, but is the timestamp assumed to be in the user's local timezone or GMT?

**Comment by prenagha** [comment] 2018-07-05 22:01
@freron one other issue... I setup a mailbox condition of `x-snooze does not exist`, saves ok, close and reopen and the UI has switched that to `x-snooze not within last 1 days`

**Comment by prenagha** [comment] 2018-07-05 22:08
Based on testing looks like the date is assumed to be UTC, so we are good. Looks like this is working now, other than the minor UI issue above. Resolving issue. Thanks all for the help getting this to work

**Closed as completed by prenagha** 2018-07-05 22:08 UTC

**Comment by freron** [comment] 2018-07-06 09:14
I've fixed the editing of “date exists” conditions in the next update. Surprisingly, I don't think this has worked in a long time, if ever. Thanks for letting me know.

Dates are UTC.

**Comment by prenagha** [comment] 2018-07-09 22:26
@freron not seeing messages "wake-up" when their X-Snooze date has past
Does something periodically scan mailbox contents for messages that newly satisfy date conditions based on the passage of time?
How often does that run?
Something I can do to debug this?

**Comment by freron** [comment] 2018-07-10 10:54
Rules are not “dynamic”. They are only triggered when messages “enter” the mailbox. If this is the problem then create a smart mailbox with the date condition instead and then have a rule with just the action. Smart mailboxes with date conditions update exactly when the date condition is met.

If this is not the issue then we need to debug.

**Comment by prenagha** [comment] 2018-07-11 18:25
Test Case:

Setup Smart Mailbox, linked to `/Later` folder with mailbox condition:
  `filter = "x-snooze < 0 days ago"` (from `Mailboxes.plist`)

Local time is 7/10/18 (Eastern US, -4) 12:24 pm, GMT 16:24

Run bundle command "Tomorrow" on message

This sets the header `X-Snooze: 2018-07-11 10:00:00` (from Raw Message View) (tomorrow 6am ET)

Message correctly does not appear in Smart Mailbox

Use Mac rest of day, close lid, sleeps overnight
Open, Login, look at MailMate at 9am ET next day

Message is not appearing in the Smart Mailbox
Even now, 2pm ET, if I uncheck the condition in the Mailbox, the message appears, then I recheck the condition, the message disappears.

At this point current time is well beyond the Snooze value, so expecting the message to appear.

Note, I did a similar test yesterday with a 5 minute snooze, and it correctly appeared. Maybe it has to do with the mac going to sleep, or the message passing the date while the Mac is sleeping

@freron Let me know what to try/debug

**Comment by prenagha** [comment] 2018-07-12 02:33
No rush @freron , I know you are on vacation. This can wait

**Comment by freron** [comment] 2018-07-13 09:49
As long as MailMate was open when you put the computer to sleep, it 
should still work (trigger rules). In any case, the message should of 
course also show up in the smart mailbox if relaunching MailMate. This 
appears to be the main problem. What if you change the condition, does 
that trigger the message to show up?
